env:
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - standard
  - prettier
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  no-console:
    - off
  no-var:
    - error
  prefer-const:
    - error
  prefer-rest-params:
    - warn
  prefer-spread:
    - warn
  prefer-template:
    - warn
